name: ShopUI
main: PiggyShopUI\Main
version: 1.0.0
api: [3.0.0, 4.0.0]
load: POSTWORLD
author: DaPigGuy
authors: JackCasto
permissions:
  shopui:
    default: false
    description: "Use Everything In ShopUI"
    children:
      shopui.command:
        default: op
        description: "Use All ShopUI Commands"
        children:
          shopui.command.shopui:
            default: true
            description: "Use /shop"
